Fixed issue with scheduler.step not being called
DETAILS:
- The cause of this issue is that the `PeftModel`, which is `PEFT`'s wrapper around any model implementing `peft.tuners.tuners_utils.BaseTuner`, provides an api function `get_base_model`, which by default returns the target model (e.g. roBERTa) instead of the BaseTuner, and as a result the BaseTuner's call method is never invoked
- Overwritten the `get_base_model` method in  `utils.wrappers.PeftModelWrapper` to force it to return the `DynaLoraModel`.
- This gave the error ([[#full error]]):
```
IndexError: Invalid key: 8431 is out of bounds for size 0
```
- And is caused within the `transformers.Trainer` instance, when the dataloader is initialised.
	- Essentially, it drops "unused" columns from the (tokenised) input data, based on the base model's forward signature. In our case, the 'base model' is the `DynaLoraInstance` and it has forward signature `(*args, **kwargs)`, which does not match any column names.
- To solve this, we need to set
	- `hf_args.remove_unused_columns = False` in the train.py script, before the Trainer is initialised and remove these columns manually.
	- To remain target-model-agnostic, I added a function that mimics the `Trainer` class' `_remove_unused_columns` method, which drops all columns of the input dataset which do not match any of the target model's forward function signature.
	- In case of roBERTa, the signature is
```
(input_ids: Optional = Noneattention_mask: Optional = Nonetoken_type_ids: Optional = Noneposition_ids: Optional = Nonehead_mask: Optional = Noneinputs_embeds: Optional = Nonelabels: Optional = Noneoutput_attentions: Optional = Noneoutput_hidden_states: Optional = Nonereturn_dict: Optional = None)
```